#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
    health:
      show-details: always

zuul:
  #设置Hystrix隔离策略为线程池
  ribbon-isolation-strategy: thread
  thread-pool:
    #每个路由使用独立的线程池
    use-separate-thread-pools: true
